name: Master Updated
on:
  push:
    branches: 
      - master

jobs:
  bump_version_number:
    runs-on: ubuntu-latest
    outputs:
      new_version: ${{ steps.bump.outputs.new_tag }}
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 0
      - name: Bump version and push tag
        id: bump
        uses: mathieudutour/github-tag-action@v4.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: false

  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
      - run: npm install --global surge
      - run: surge landing-pages --token ${{ secrets.SURGE_TOKEN }}
        
  discord_notify_deployed:
    needs: bump_version_number
    runs-on: ubuntu-latest
    name: PreLaunch Page Deployed
    steps:
      - uses: actions/checkout@v1
      - name: Deployment
        uses: rjstone/discord-webhook-notify@v1.0.4
        with:
          severity: info
          username: KoWT
          details: "**${{ needs.bump_version_number.outputs.new_version }}**\nThe PreLaunch Page has been deployed.\nURL: http://kingsofwar.carlsonmckinnon.com."
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
