name: Pull Request Opened
on:
  pull_request_target:
    types: [opened]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Obtain a code review approval before merging pull request.'
            })

            github.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['awaiting review']
            })
           
  discord_notify_pull_request_review:
    runs-on: ubuntu-latest
    name: Pull Request Needs Review
    steps:
      - name: Pull Request
        uses: rjstone/discord-webhook-notify@v1.0.4
        with:
          severity: info
          username: KoWT
          description: "A Pull Request is awaiting review...\n\n- **Name:** ${{ github.event.pull_request.title }}\n- **Author:** ${{ github.event.pull_request.user.login }}\n- **URL:** ${{ github.event.pull_request.html_url }}"
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
