name: Pull Request Opened
on:
  pull_request_target:
    types: [opened]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Obtain a code review approval before merging pull request.'
            })

            github.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['awaiting review']
            })
           
  discord_notify_pullRequest_Review:
        name: Pull Request Needs Review
        runs-on: ubuntu-latest
        steps:
            - name: Pull Request
              if: ${{ contains(github.event.pull_request.labels.*.name, 'awaiting review') }}
              uses: rjstone/discord-webhook-notify@v1
              with:
                severity: warn
                username: KoWT
                details: A Pull Request is Awaiting Review.
                webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}         
