name: Verify and Update Version
on:
  push:
    branches: 
      - master

jobs:
  angular_ci:
    runs-on: ubuntu-latest
    name: Test & lint app
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - name: install packages
        run: sudo npm install
      - name: Check angular version (npx)
        run: npx ng v
      - name: Build angular app
        id: build
        run: |
          echo "\n*** Pre-Deployment Tests: Building Angular App ***\n"
          npm run build
      - name: Run angular tests
        id: test
        run: |
          echo "\n*** Pre-Deployment Tests: Running Tests ***\n"
          npm run test:ci
      - name: Run end-to-end tests
        id: e2e
        run: |
          echo "\n *** Pre-Deployment Tests: Running E2E Tests ***\n"
          npm run e2e
      - name: Lint angular app
        id: lint
        run: |
          echo "\n*** Pre-Deployment Tests: Linting Project ***\n"
          npm run lint

  calculate_next_version:
    needs: angular_ci
    runs-on: ubuntu-latest
    outputs:
      prev_tag: ${{ steps.calc_version.outputs.previous_tag }}
      next_tag: ${{ steps.calc_version.outputs.new_tag }}
      next_version: ${{ steps.calc_version.outputs.new_version }}
    name: Calculate next version
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Calculate new version
        id: calc_version
        uses: mathieudutour/github-tag-action@v5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: false
          dry_run: true
  
  update_version:
    needs: [ angular_ci, calculate_next_version ]
    runs-on: ubuntu-latest
    if: ${{ needs.calculate_next_version.outputs.next_version }}
    name: Update npm version
    steps:
      - name: checkout_master
        uses: actions/checkout@v2
        with:
          ref: master
      - name: Bump npm version, commit and push
        id: bump_npm
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git status
          npm version ${{ needs.calculate_next_version.outputs.next_version }} -m "doc: update version to %s"
          git push --follow-tags
